# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
  paths:
    include:
    - 'src/*'
    - '*.json'
    - 'server.ts'
      
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.15.1'
  displayName: 'Install Node.js (v14.15.1)'

- script: |
    npm install -g @angular/cli@10.1.4
    npm install
    npm run build:ssr
  displayName: 'Installing Anguler v10.1.4 and packages'

- script: |
    npm run build:ssr
  displayName: 'Bulild SSR with npm'

- script: |
    ls $(Build.SourcesDirectory)
  displayName: 'List Built artefacts'

- publish: $(System.DefaultWorkingDirectory)/dist
  artifact: dist
  displayName: 'Publish dist dir'